
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

#Dota 2 Rules
windowrule {
    name = dota2_rules
    match:class = ^(dota2)$

    fullscreen = 1
    workspace = 10
}
# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#Workspace rules

# Workspace fixo no monitor
workspace = 10, monitor:HDMI-A-1


# Monitor Configs
monitor=DP-1,1366x768@59,0x0,1
monitor=HDMI-A-1,1920x1080@60,1366x0,1